In [1]:
import torch

In [6]:
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 4.6566e-10, 6.1161e-17],
        [3.6902e+19, 5.6052e-45, 4.6566e-10],
        [6.1220e-17, 8.5920e+09, 1.3553e-19],
        [4.5071e+16, 8.1153e+17, 1.1720e-19],
        [2.9503e-39, 0.0000e+00, 0.0000e+00]])


In [7]:
x = torch.rand(5, 3)
print(x)

tensor([[0.8361, 0.9084, 0.8346],
        [0.2365, 0.3530, 0.1282],
        [0.4218, 0.1009, 0.8349],
        [0.0722, 0.7076, 0.1668],
        [0.3123, 0.7579, 0.5196]])


In [8]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [9]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [12]:
x = x.new_zeros(5, 3, dtype=torch.double)
print(x)
x = torch.rand_like(x, dtype=torch.float)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)
tensor([[0.1663, 0.1567, 0.4873],
        [0.1848, 0.5092, 0.3348],
        [0.7744, 0.9168, 0.6665],
        [0.5762, 0.7400, 0.1815],
        [0.8843, 0.5101, 0.4507]])


In [13]:
print(x.size())

torch.Size([5, 3])


In [14]:
y = torch.rand(5, 3)
print(x + y)

tensor([[0.7685, 0.8714, 0.6374],
        [1.0186, 0.6624, 0.4268],
        [1.4507, 1.2768, 0.7658],
        [0.7223, 1.4829, 1.0609],
        [0.9224, 1.3732, 0.9283]])


In [15]:
print(torch.add(x, y))

tensor([[0.7685, 0.8714, 0.6374],
        [1.0186, 0.6624, 0.4268],
        [1.4507, 1.2768, 0.7658],
        [0.7223, 1.4829, 1.0609],
        [0.9224, 1.3732, 0.9283]])


In [16]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.7685, 0.8714, 0.6374],
        [1.0186, 0.6624, 0.4268],
        [1.4507, 1.2768, 0.7658],
        [0.7223, 1.4829, 1.0609],
        [0.9224, 1.3732, 0.9283]])


In [17]:
print(y)

tensor([[0.6022, 0.7147, 0.1501],
        [0.8337, 0.1533, 0.0920],
        [0.6763, 0.3600, 0.0994],
        [0.1461, 0.7429, 0.8794],
        [0.0381, 0.8631, 0.4776]])


In [18]:
y.add_(x)
print(y)

tensor([[0.7685, 0.8714, 0.6374],
        [1.0186, 0.6624, 0.4268],
        [1.4507, 1.2768, 0.7658],
        [0.7223, 1.4829, 1.0609],
        [0.9224, 1.3732, 0.9283]])


In [19]:
x[:, 1]

tensor([0.1567, 0.5092, 0.9168, 0.7400, 0.5101])

In [20]:
x = torch.rand(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [25]:
x = torch.rand(1)
print(x)
print(x.item())

tensor([0.4567])
0.45669764280319214


In [27]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [28]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [29]:
a.add_(1)
print(a, b)

tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]


In [30]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
