# Official Tutorial

In [1]:
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 2.0000e+00, 4.9742e-14],
        [8.5920e+09, 1.2677e+31, 3.2745e-12],
        [1.7743e+28, 2.0535e-19, 3.0478e+32],
        [1.4332e-19, 2.7530e+12, 7.5338e+28],
        [7.8595e+31, 8.6881e-44, 0.0000e+00]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.9788, 0.2017, 0.8435],
        [0.5306, 0.6925, 0.8643],
        [0.6977, 0.0278, 0.7762],
        [0.4761, 0.6116, 0.0168],
        [0.7698, 0.5741, 0.0443]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_zeros(5, 3, dtype=torch.double)
print(x)
x = torch.rand_like(x, dtype=torch.float)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)
tensor([[0.1771, 0.7177, 0.3300],
        [0.8619, 0.3637, 0.9655],
        [0.2933, 0.3518, 0.4369],
        [0.9956, 0.1865, 0.9680],
        [0.3921, 0.1299, 0.2584]])


In [7]:
print(x.size())

torch.Size([5, 3])


In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[0.6562, 1.3273, 0.7194],
        [1.1542, 0.9602, 1.9005],
        [0.5206, 0.8816, 1.1463],
        [1.3391, 0.5239, 1.5074],
        [1.3518, 0.5797, 0.2790]])


In [9]:
print(torch.add(x, y))

tensor([[0.6562, 1.3273, 0.7194],
        [1.1542, 0.9602, 1.9005],
        [0.5206, 0.8816, 1.1463],
        [1.3391, 0.5239, 1.5074],
        [1.3518, 0.5797, 0.2790]])


In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.6562, 1.3273, 0.7194],
        [1.1542, 0.9602, 1.9005],
        [0.5206, 0.8816, 1.1463],
        [1.3391, 0.5239, 1.5074],
        [1.3518, 0.5797, 0.2790]])


In [11]:
print(y)

tensor([[0.4791, 0.6096, 0.3894],
        [0.2923, 0.5965, 0.9350],
        [0.2273, 0.5298, 0.7094],
        [0.3435, 0.3374, 0.5394],
        [0.9597, 0.4498, 0.0207]])


In [12]:
y.add_(x)
print(y)

tensor([[0.6562, 1.3273, 0.7194],
        [1.1542, 0.9602, 1.9005],
        [0.5206, 0.8816, 1.1463],
        [1.3391, 0.5239, 1.5074],
        [1.3518, 0.5797, 0.2790]])


In [13]:
x[:, 1]

tensor([0.7177, 0.3637, 0.3518, 0.1865, 0.1299])

In [14]:
x = torch.rand(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [15]:
x = torch.rand(1)
print(x)
print(x.item())

tensor([0.4726])
0.47260189056396484


In [16]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [17]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [18]:
a.add_(1)
print(a, b)

tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]


In [19]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# [Community Tutorial](https://github.com/yunjey/pytorch-tutorial/blob/master/tutorials/01-basics/pytorch_basics/main.py)

In [20]:
import torch
import torchvision
import torch.nn as nn
import numpy as np
import torchvision.transforms as transforms

### Autograd

In [21]:
x = torch.tensor(1., requires_grad=True)
w = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)

y = w * x + b # build computational graph

y.backward() # compute gradients

print(x.grad)
print(w.grad)
print(b.grad)

tensor(2.)
tensor(1.)
tensor(1.)


In [24]:
x = torch.randn(10, 3)
y = torch.randn(10, 2)

linear = nn.Linear(3, 2) # FC layer
print('w: ', linear.weight)
print('b: ', linear.bias)

criterion = nn.MSELoss() # choose loss function
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

pred = linear(x) # forward pass
loss = criterion(pred, y) # loss
print('loss: ', loss.item())

loss.backward()
print('dL/dw: ', linear.weight.grad)
print('dL/db: ', linear.bias.grad)

optimizer.step()
# linear.weight.data.sub_(0.01 * linear.weight.grad.data)
# linear.bias.data.sub_(0.01 * linear.bias.grad.data)


pred = linear(x)
loss = criterion(pred, y)
print('loss after 1 step optim: ', loss.item())

w:  Parameter containing:
tensor([[-0.2817, -0.4402, -0.0546],
        [-0.2890,  0.2279,  0.3990]], requires_grad=True)
b:  Parameter containing:
tensor([0.3324, 0.2330], requires_grad=True)
loss:  1.2076702117919922
dL/dw:  tensor([[-0.8939, -0.8807, -0.1907],
        [-0.7563, -0.0153, -0.0301]])
dL/db:  tensor([ 0.0347, -0.3225])
loss after 1 step optim:  1.1850112676620483


### Numpy

In [27]:
x = np.array([[1, 2], [3, 4]])
y = torch.from_numpy(x)
z = y.numpy()

print(x)
print(y)
print(z)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])
[[1 2]
 [3 4]]


### Input pipeline

In [31]:
train_dataset = torchvision.datasets.CIFAR10(root='./data',
                                             train=True,
                                             transform=transforms.ToTensor(),
                                             download=True)
image, label = train_dataset[0]
print(image.size())
print(label)

Files already downloaded and verified
torch.Size([3, 32, 32])
6


In [34]:
train_loader = torch.utils.data.DataLoader(dataset=train_dataset,
                                           batch_size=64,
                                           shuffle=True)

data_iter = iter(train_loader)
images, labels = data_iter.next()
print("size of one mini-batch: ", images.size(), labels.size())

size of one mini-batch:  torch.Size([64, 3, 32, 32]) torch.Size([64])


In [33]:
for images, labels in train_loader:
    pass

### Create custom dataset pipeline

In [39]:
class CustomDataset(torch.utils.data.Dataset):
    def __init__(self):
        # Initialize file path
        pass
    
    def __getitem__(self, index):
        # 1. Read one batch from file, numpy.fromfile
        # 2. Pre-process the data, using torchvision.transform
        # 3. Return a data pair
        return (1, 2)
    
    def __len__(self):
        # total size of dataset
        return 1

custom_dataset = CustomDataset()
train_loader = torch.utils.data.DataLoader(dataset=custom_dataset,
                                           batch_size=64,
                                           shuffle=True)
data_iter = iter(train_loader)
images, labels = data_iter.next()
print(images, labels)

tensor([1]) tensor([2])


### Pretrained model

In [43]:
# Download and load pretrained ResNet-18
resnet = torchvision.models.resnet18(pretrained=True)

In [44]:
# Only tune the top layer of the model
for param in resnet.parameters():
    param.requires_grad = False

# Replace the FC for finetuning.
resnet.fc = nn.Linear(resnet.fc.in_features, 100)

images = torch.randn(64, 3, 224, 224)
outputs = resnet(images)
print(outputs.size())

torch.Size([64, 100])


### Save and load models

In [45]:
# Save and load the entire model.
torch.save(resnet, 'model.ckpt')
model = torch.load('model.ckpt')

In [47]:
!du -sh model.ckpt

 43M	model.ckpt


In [50]:
# Save and load only the model params. Recommended.
torch.save(resnet.state_dict(), 'params.ckpt')
resnet.load_state_dict(torch.load('params.ckpt'))

In [55]:
!du -sh params.ckpt

 43M	params.ckpt
