In [2]:
import numpy as np

d = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])

In [4]:
cal = d.sum(axis=0)

In [8]:
result = 100 * d / cal
print(result)

[[ 8.33333333 13.33333333 16.66666667]
 [33.33333333 33.33333333 33.33333333]
 [58.33333333 53.33333333 50.        ]]


In [11]:
a = np.random.randn(5)
print(a)

[-1.14688771  0.87853804 -0.81867814 -1.02232243  2.45682175]


In [12]:
print(a.T)

[-1.14688771  0.87853804 -0.81867814 -1.02232243  2.45682175]


In [13]:
b = np.random.randn(5, 1)
print(b)

[[-0.33719236]
 [-0.05961733]
 [ 1.07733617]
 [-1.59058133]
 [ 0.84478366]]


In [14]:
print(b.T)

[[-0.33719236 -0.05961733  1.07733617 -1.59058133  0.84478366]]


In [35]:
a = ['a','b', 'c', 'a','c']
# b = [1,2,3]

a[1:4]=[]
# a.remove('a') # remove by value
# a.pop(2) # remove by index
# del(a[1:3]) # remove multiple elements
# a.pop() # remove the last element

print(a)

['a', 'c']
